baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'DIDU Real Estate'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'About'
    pageRef = '/About'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
